name: LAPRAS Card Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-card:
    name: LAPRAS Card
    runs-on: ubuntu-latest
    steps:
      - uses: kawamataryo/lapras-card-readme@v1.2.1
        with:
          SHARE_ID: "4CO6I1I"
          LANG: "en"
